on:
  workflow_dispatch:
  push:
  release:
    types: [released]

env:
  VERSION: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.19'
    - name: deps
      run: go mod download
    - name: test
      run : make test
    - name: build
      run: |
        GOARCH=arm64 make --always-make module.tgz && mv module.tgz module-arm64.tgz
        GOARCH=amd64 make --always-make module.tgz && mv module.tgz module-amd64.tgz
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module-arm64.tgz
        platform: linux/arm64
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
    - uses: viamrobotics/upload-module@main
      if: github.event_name == 'release'
      with:
        module-path: module-amd64.tgz
        platform: linux/amd64
        version: ${{ env.VERSION }}
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
